
# beware whitespaces

version: "3.9"

services:
 db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: "Senha123"
   MYSQL_DATABASE: "mainDB"
  ports:
   - "3306:3306"
  volumes:
   - /data/mysql:/var/lib/mysql
  networks:
   - minha-rede

adminer:
 image: adminer
 ports:
  - 8080:8080
 networks:
  - minha-rede

networks: 
 minha-rede:
  driver: bridge