
# beware whitespaces

version: "3.9"

services:
 web:
  image: webdevops/php-apache:alpine-php7
  ports:
   - "80:80"
  volumes:
   - ./docker-lamp/:/app/
  networks:
   - minha-rede

 db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: "Senha123"
   MYSQL_DATABASE: "mainDB"
  ports:
   - "3306:3306"
  volumes:
   - /data/mysql:/var/lib/mysql
  networks:
   - minha-rede

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   MYSQL_ROOT_PASSWORD: "Senha123"
  ports:
   - "8080:80"
  volumes:
   - ./docker-lamp/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  networks:
   - minha-rede

networks:
 minha-rede:
  driver: bridge
